name: movemedical_api
description: Move Medical API

version: 0.9.0

environment:
  sdk: ">=2.1.0-dev.9.4 <3.0.0"

dependencies:
  http: ^0.12.0+1
  modux:
    path: ../modux-dart
#    git: git://github.com/movemedical/modux-dart

dev_dependencies:
  analyzer: ^0.35.4
  build: ^1.1.3
  build_runner: ^1.3.1
  test: ^1.6.2
  mockito: ^4.0.0
#  build_web_compilers: ^1.1.0

  built_value_generator:
#    path: ../built-value-generator
    git: git://github.com/movemedical/built-value-generator
  modux_generator:
#    path: ../modux-dart-generator
    git: git://github.com/movemedical/modux-dart-generator
